# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: margrete/rpc/v1/messages.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'margrete/rpc/v1/messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1emargrete/rpc/v1/messages.proto\x12\x0fmargrete.rpc.v1\"\xe8\x02\n\x08\x45nvelope\x12\x12\n\nrequest_id\x18\x01 \x01(\x04\x12\x34\n\x0cping_request\x18\n \x01(\x0b\x32\x1c.margrete.rpc.v1.PingRequestH\x00\x12\x36\n\rping_response\x18\x0b \x01(\x0b\x32\x1d.margrete.rpc.v1.PingResponseH\x00\x12J\n\x18get_current_tick_request\x18\x14 \x01(\x0b\x32&.margrete.rpc.v1.GetCurrentTickRequestH\x00\x12L\n\x19get_current_tick_response\x18\x15 \x01(\x0b\x32\'.margrete.rpc.v1.GetCurrentTickResponseH\x00\x12\x38\n\x0e\x65rror_response\x18\x64 \x01(\x0b\x32\x1e.margrete.rpc.v1.ErrorResponseH\x00\x42\x06\n\x04\x62ody\"\r\n\x0bPingRequest\"#\n\x0cPingResponse\x12\x13\n\x0bserver_name\x18\x01 \x01(\t\"\x17\n\x15GetCurrentTickRequest\"&\n\x16GetCurrentTickResponse\x12\x0c\n\x04tick\x18\x01 \x01(\x05\"J\n\rErrorResponse\x12(\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1a.margrete.rpc.v1.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t*\xa1\x01\n\tErrorCode\x12\x1a\n\x16\x45RROR_CODE_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x45RROR_CODE_UNAVAILABLE\x10\x01\x12\x1f\n\x1b\x45RROR_CODE_INVALID_ARGUMENT\x10\x02\x12\"\n\x1e\x45RROR_CODE_FAILED_PRECONDITION\x10\x03\x12\x17\n\x13\x45RROR_CODE_INTERNAL\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'margrete.rpc.v1.messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORCODE']._serialized_start=608
  _globals['_ERRORCODE']._serialized_end=769
  _globals['_ENVELOPE']._serialized_start=52
  _globals['_ENVELOPE']._serialized_end=412
  _globals['_PINGREQUEST']._serialized_start=414
  _globals['_PINGREQUEST']._serialized_end=427
  _globals['_PINGRESPONSE']._serialized_start=429
  _globals['_PINGRESPONSE']._serialized_end=464
  _globals['_GETCURRENTTICKREQUEST']._serialized_start=466
  _globals['_GETCURRENTTICKREQUEST']._serialized_end=489
  _globals['_GETCURRENTTICKRESPONSE']._serialized_start=491
  _globals['_GETCURRENTTICKRESPONSE']._serialized_end=529
  _globals['_ERRORRESPONSE']._serialized_start=531
  _globals['_ERRORRESPONSE']._serialized_end=605
# @@protoc_insertion_point(module_scope)
