"""Domain models."""

from margrete_rpc.model.chart import Chart, ChartEvents, MgChart, normalize_event_operations
from margrete_rpc.model.chart_time import Position, p2t, t2p
from margrete_rpc.model.constant import TICKS_PER_BEAT
from margrete_rpc.model.event import (
    BeatEvent,
    BpmEvent,
    NoteSpeedEvent,
    TimelineSpeedEvent,
)
from margrete_rpc.model.note import (
    Air,
    AirCrush,
    AirCrushColor,
    AirCrushOption,
    AirDirection,
    AirDirectionLike,
    AirHold,
    AirSlide,
    Damage,
    Direction,
    DirectionValue,
    ExAttr,
    Extap,
    ExtapDirection,
    ExtapDirectionLike,
    Flick,
    FlickDirection,
    FlickDirectionLike,
    Hold,
    Joint,
    LongAttr,
    M,
    MgNote,
    Note,
    NoteInfo,
    NoteType,
    Slide,
    Tap,
    UnsupportedNoteTree,
    wrap_mg_note,
)

__all__ = [
    "Air",
    "AirDirection",
    "AirDirectionLike",
    "AirCrush",
    "AirHold",
    "AirSlide",
    "AirCrushColor",
    "AirCrushOption",
    "BeatEvent",
    "BpmEvent",
    "Chart",
    "ChartEvents",
    "Damage",
    "Direction",
    "DirectionValue",
    "ExAttr",
    "Extap",
    "ExtapDirection",
    "ExtapDirectionLike",
    "Flick",
    "FlickDirection",
    "FlickDirectionLike",
    "Note",
    "Hold",
    "Joint",
    "M",
    "MgChart",
    "MgNote",
    "LongAttr",
    "NoteInfo",
    "NoteSpeedEvent",
    "NoteType",
    "Position",
    "p2t",
    "Slide",
    "Tap",
    "t2p",
    "TICKS_PER_BEAT",
    "TimelineSpeedEvent",
    "UnsupportedNoteTree",
    "normalize_event_operations",
    "wrap_mg_note",
]
