"""Domain models."""

from margrete_rpc.model.chart import Chart, ChartEvents, LLChart, normalize_event_operations
from margrete_rpc.model.event import (
    BeatEvent,
    BpmEvent,
    NoteSpeedEvent,
    TimelineSpeedEvent,
)
from margrete_rpc.model.note import (
    AirCrush,
    AirCrushColor,
    AirCrushOption,
    AirDirection,
    Damage,
    ExAttr,
    Extap,
    ExtapDirection,
    Flick,
    FlickDirection,
    HLNote,
    Hold,
    Joint,
    L,
    LLNote,
    LongAttr,
    NoteInfo,
    NoteType,
    Slide,
    Tap,
    TICKS_PER_BEAT,
    UnsupportedNoteTree,
    b2t,
    beats_to_ticks,
    t2b,
    ticks_to_beats,
    wrap_ll_note,
)

__all__ = [
    "AirDirection",
    "AirCrush",
    "AirCrushColor",
    "AirCrushOption",
    "BeatEvent",
    "BpmEvent",
    "Chart",
    "ChartEvents",
    "Damage",
    "ExAttr",
    "Extap",
    "ExtapDirection",
    "Flick",
    "FlickDirection",
    "HLNote",
    "Hold",
    "Joint",
    "L",
    "LLChart",
    "LLNote",
    "LongAttr",
    "NoteInfo",
    "NoteSpeedEvent",
    "NoteType",
    "Slide",
    "Tap",
    "TICKS_PER_BEAT",
    "TimelineSpeedEvent",
    "b2t",
    "beats_to_ticks",
    "t2b",
    "ticks_to_beats",
    "UnsupportedNoteTree",
    "normalize_event_operations",
    "wrap_ll_note",
]
